# Generated by Django 5.2.7 on 2025-12-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('rol', models.CharField(choices=[('PROCESOS', 'Administrador de Procesos'), ('UBICACIONES', 'Administrador de Ubicaciones'), ('SUPER', 'Super administrador')], default='PROCESOS', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
