# Generated by Django 5.2.7 on 2025-11-05 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadResponsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Paso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iden', models.CharField(max_length=45)),
                ('actividad', models.TextField()),
                ('tiempo_estimado', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Procesos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RequisitoProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PasoResponsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='Procesos.entidadresponsable')),
                ('paso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='Procesos.paso')),
            ],
        ),
        migrations.AddField(
            model_name='paso',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='Procesos.procesos'),
        ),
        migrations.CreateModel(
            name='RequisitoPaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('paso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='Procesos.paso')),
            ],
        ),
        migrations.CreateModel(
            name='ProcesosRequisitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Procesos.procesos')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Procesos.requisitoproceso')),
            ],
            options={
                'unique_together': {('proceso', 'requisito')},
            },
        ),
        migrations.AddField(
            model_name='procesos',
            name='requisitos',
            field=models.ManyToManyField(related_name='procesos', through='Procesos.ProcesosRequisitos', to='Procesos.requisitoproceso'),
        ),
    ]
