# Generated by Django 4.2.26 on 2025-12-10 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Procesos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='procesosrequisitos',
            table='Procesos_requisitoproceso',
        ),
        migrations.AlterModelTable(
            name='requisitoproceso',
            table='Procesos_requisitoproceso_base',
        ),
    ]
