# Generated by Django 4.2.26 on 2025-12-10 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Procesos', '0002_alter_procesosrequisitos_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='procesosrequisitos',
            table=None,
        ),
        migrations.AlterModelTable(
            name='requisitoproceso',
            table=None,
        ),
    ]
