# Generated by Django 4.2.25 on 2025-11-02 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nom_nodo', models.CharField(blank=True, max_length=45, null=True, unique=True, verbose_name='Nombre del Nodo')),
                ('pos_x', models.FloatField(help_text='Coordenada X en píxeles')),
                ('pos_y', models.FloatField(help_text='Coordenada Y en píxeles')),
                ('tipo', models.CharField(choices=[('edificio', 'Edificio'), ('intermedio', 'Punto Intermedio')], default='intermedio', help_text='Define si es un nodo asociado a un edificio o solo un punto de ruta', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'ubicacion',
                'ordering': ['nom_nodo'],
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id_edificio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('uso', models.CharField(max_length=500)),
                ('num_salones', models.IntegerField(default=0)),
                ('carreras', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edificios', to='mapa.ubicacion')),
            ],
            options={
                'verbose_name': 'Edificio',
                'verbose_name_plural': 'Edificios',
                'db_table': 'edificio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RelacionU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.FloatField(blank=True, help_text='Distancia euclidiana en píxeles', null=True)),
                ('peso', models.FloatField(blank=True, help_text='Peso o costo de la conexión (puede ser distinto a la distancia)', null=True)),
                ('bidireccional', models.BooleanField(default=True, help_text='Si es True, se crea conexión inversa automáticamente')),
                ('destino', models.ForeignKey(db_column='id_destino', on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_entrada', to='mapa.ubicacion')),
                ('origen', models.ForeignKey(db_column='id_origen', on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_salida', to='mapa.ubicacion')),
            ],
            options={
                'verbose_name': 'Relación entre ubicaciones',
                'verbose_name_plural': 'Relaciones entre ubicaciones',
                'db_table': 'relacion_u',
                'unique_together': {('origen', 'destino')},
            },
        ),
    ]
