# Generated by Django 4.2.25 on 2025-11-02 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edificio',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='relacionu',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'ordering': ['nom_nodo']},
        ),
        migrations.AlterField(
            model_name='edificio',
            name='uso',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='relacionu',
            name='bidireccional',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='relacionu',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_entrada', to='mapa.ubicacion'),
        ),
        migrations.AlterField(
            model_name='relacionu',
            name='distancia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relacionu',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_salida', to='mapa.ubicacion'),
        ),
        migrations.AlterField(
            model_name='relacionu',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='nom_nodo',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='tipo',
            field=models.CharField(choices=[('edificio', 'Edificio'), ('intermedio', 'Punto Intermedio')], default='intermedio', max_length=20),
        ),
    ]
