# Generated by Django 4.2.25 on 2025-11-06 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0002_alter_edificio_options_alter_relacionu_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='pos_x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='pos_y',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='tipo',
            field=models.CharField(choices=[('edificio', 'Edificio'), ('intermedio', 'Punto Intermedio'), ('calle', 'Calle')], default='intermedio', max_length=20),
        ),
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('id_calle', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre de la calle', max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción adicional', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ubicacion', models.ForeignKey(help_text='Ubicación en el mapa', on_delete=django.db.models.deletion.CASCADE, related_name='calles', to='mapa.ubicacion')),
            ],
            options={
                'verbose_name': 'Calle',
                'verbose_name_plural': 'Calles',
                'db_table': 'calle',
                'ordering': ['nombre'],
            },
        ),
    ]
