# Generated by Django 4.2.25 on 2025-11-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0003_alter_ubicacion_pos_x_alter_ubicacion_pos_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='tipo',
            field=models.CharField(choices=[('edificio', 'Edificio'), ('intermedio', 'Punto Intermedio')], default='intermedio', max_length=20),
        ),
        migrations.DeleteModel(
            name='Calle',
        ),
    ]
