# Generated by Django 5.2.7 on 2025-12-08 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id_edificio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('nombre_especial', models.CharField(blank=True, max_length=150, null=True)),
                ('uso', models.CharField(blank=True, max_length=500)),
                ('num_salones', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ubicaciones_edificio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoArea',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'ubicaciones_tipo_area',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nom_nodo', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('pos_x', models.FloatField()),
                ('pos_y', models.FloatField()),
                ('tipo', models.CharField(choices=[('edificio', 'Edificio'), ('intermedio', 'Punto Intermedio')], default='intermedio', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ubicaciones_ubicacion',
                'ordering': ['nom_nodo'],
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id_salon', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20)),
                ('capacidad', models.IntegerField(default=30)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salones', to='Ubicaciones.edificio')),
            ],
            options={
                'db_table': 'ubicaciones_salon',
                'ordering': ['edificio', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='AreaEdificio',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='Ubicaciones.edificio')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='Ubicaciones.tipoarea')),
            ],
            options={
                'db_table': 'ubicaciones_areas_edificio',
                'ordering': ['edificio', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='edificio',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edificios', to='Ubicaciones.ubicacion'),
        ),
        migrations.CreateModel(
            name='RelacionU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.FloatField(blank=True, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('bidireccional', models.BooleanField(default=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_entrada', to='Ubicaciones.ubicacion')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_salida', to='Ubicaciones.ubicacion')),
            ],
            options={
                'db_table': 'ubicaciones_relacion_u',
                'unique_together': {('origen', 'destino')},
            },
        ),
    ]
