# Generated by Django 5.2.8 on 2025-11-16 17:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edificio',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='salon',
            options={'ordering': ['edificio', 'numero']},
        ),
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'ordering': ['nom_nodo']},
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='id',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='id',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='piso',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='nombre_nodo',
        ),
        migrations.AddField(
            model_name='edificio',
            name='carreras',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='edificio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edificio',
            name='id_edificio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='relacionu',
            name='bidireccional',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='relacionu',
            name='distancia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relacionu',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='id_salon',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='salon',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='id_ubicacion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='nom_nodo',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='tipo',
            field=models.CharField(choices=[('edificio', 'Edificio'), ('intermedio', 'Punto Intermedio')], default='intermedio', max_length=20),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='nombre',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='num_salones',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='uso',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='relacionu',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_entrada', to='Ubicaciones.ubicacion'),
        ),
        migrations.AlterField(
            model_name='relacionu',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_salida', to='Ubicaciones.ubicacion'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='capacidad',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='salon',
            name='numero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterModelTable(
            name='edificio',
            table='edificio',
        ),
        migrations.AlterModelTable(
            name='relacionu',
            table='relacion_u',
        ),
        migrations.AlterModelTable(
            name='salon',
            table='salon',
        ),
        migrations.AlterModelTable(
            name='ubicacion',
            table='ubicacion',
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
