# Generated by Django 5.2.7 on 2025-12-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificio',
            name='edificio_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
