# Generated by Django 5.2.7 on 2025-11-05 04:21

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo_consulta', models.CharField(choices=[('PROCESOS', 'Procesos'), ('UBICACIONES', 'Ubicaciones')], max_length=45)),
                ('tipo_consulta', models.CharField(max_length=45)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Contexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('role', models.CharField(choices=[('USER', 'Usuario'), ('ASSISTANT', 'Asistente')], max_length=20)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
