# Generated by Django 5.2.7 on 2025-12-08 00:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True)),
                ('modulo_consulta', models.CharField(choices=[('PROCESOS', 'Procesos'), ('UBICACIONES', 'Ubicaciones'), ('GENERAL', 'General')], max_length=45)),
                ('tipo_consulta', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Contexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True)),
                ('role', models.CharField(choices=[('USER', 'Usuario'), ('ASSISTANT', 'Asistente')], max_length=20)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Contexto',
                'verbose_name_plural': 'Contextos',
                'ordering': ['fecha'],
            },
        ),
    ]
