# Generated by Django 5.2.7 on 2025-12-01 22:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='session_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='modulo_consulta',
            field=models.CharField(choices=[('PROCESOS', 'Procesos'), ('UBICACIONES', 'Ubicaciones'), ('GENERAL', 'General')], max_length=45),
        ),
        migrations.AlterField(
            model_name='contexto',
            name='session_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
